server:
  port: 8086
  servlet:
    context-path:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    serialization:
      indent_output: true

mybatis:
  type-aliases-package: com.array.domain
  mapper-locations: classpath:mybatis/mapper/*.xml